mod:
  - changed-files:
      - any-glob-to-any-file: 'mods/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'
          - 'mods/*/README.md'
          - '.github/ISSUE_TEMPLATE/**'
          - '.github/PULL_REQUEST_TEMPLATE.md'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/labeler.yml'
          - '.github/dependabot.yml'
          - 'scripts/**'
